# Generated by Django 3.1.7 on 2021-03-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0027_auto_20210304_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image', verbose_name='Obrazek do artyklu'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home_image'),
        ),
        migrations.AlterField(
            model_name='storeproducts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_image', verbose_name='Obrazek do towaru'),
        ),
    ]
