# Generated by Django 3.1.7 on 2021-03-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0028_auto_20210305_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typerepair',
            name='type_repair',
            field=models.CharField(help_text='Typ naprawy(kierownica, hamulca itp)', max_length=60, unique=True),
        ),
    ]
