# Generated by Django 3.1.7 on 2021-03-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0029_auto_20210310_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name_repair',
            field=models.CharField(help_text='Nazwa naprawy(wymiana kierownicy)', max_length=60, unique=True),
        ),
    ]
