# Generated by Django 3.1.7 on 2021-03-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0030_auto_20210310_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='data_add',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storeproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cena towaru'),
        ),
    ]
